from django.contrib import admin
from home.models import  Contact, TCS, Accenture,Atos,Amazon,Capgemini,Coginzant,Delloite,IBM,Microsoft,Facebook,Apple,Netflix,Google,Infosys,Wipro,TM,Adobe,Cisco,EY,PWC

# Register your models here.
admin.site.register(Contact)
admin.site.register(TCS)
admin.site.register(Coginzant)
admin.site.register(Accenture)
admin.site.register(Amazon)
admin.site.register(Atos)
admin.site.register(Capgemini)
admin.site.register(Delloite)
admin.site.register(IBM)
admin.site.register(Microsoft)
admin.site.register(Facebook)
admin.site.register(Apple)
admin.site.register(Netflix)
admin.site.register(Google)
admin.site.register(Infosys)
admin.site.register(Wipro)
admin.site.register(TM)
admin.site.register(Adobe)
admin.site.register(Cisco)
admin.site.register(EY)
admin.site.register(PWC)