# Generated by Django 4.1.5 on 2023-02-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                ("input_format", models.CharField(max_length=200)),
                ("output_format", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Company2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                ("input_format", models.CharField(max_length=200)),
                ("output_format", models.CharField(max_length=200)),
            ],
        ),
    ]
