# Generated by Django 4.1.5 on 2023-02-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_company1_company2"),
    ]

    operations = [
        migrations.AddField(
            model_name="company1",
            name="correct_ans",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
