# Generated by Django 4.1.5 on 2023-03-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_company1_correct_ans"),
    ]

    operations = [
        migrations.CreateModel(
            name="TCS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(null=True)),
                ("input_format", models.TextField(null=True)),
                ("output_format", models.TextField(null=True)),
                ("correct_ans", models.TextField(null=True)),
            ],
        ),
    ]
