# Generated by Django 4.1.6 on 2023-04-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tcs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accenture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(null=True)),
                ('input_format', models.TextField(null=True)),
                ('output_format', models.TextField(null=True)),
                ('correct_ans', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Amazon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(null=True)),
                ('input_format', models.TextField(null=True)),
                ('output_format', models.TextField(null=True)),
                ('correct_ans', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(null=True)),
                ('input_format', models.TextField(null=True)),
                ('output_format', models.TextField(null=True)),
                ('correct_ans', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capgemini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(null=True)),
                ('input_format', models.TextField(null=True)),
                ('output_format', models.TextField(null=True)),
                ('correct_ans', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coginzant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(null=True)),
                ('input_format', models.TextField(null=True)),
                ('output_format', models.TextField(null=True)),
                ('correct_ans', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delloite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(null=True)),
                ('input_format', models.TextField(null=True)),
                ('output_format', models.TextField(null=True)),
                ('correct_ans', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IBM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(null=True)),
                ('input_format', models.TextField(null=True)),
                ('output_format', models.TextField(null=True)),
                ('correct_ans', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Microsoft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(null=True)),
                ('input_format', models.TextField(null=True)),
                ('output_format', models.TextField(null=True)),
                ('correct_ans', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Company1',
        ),
        migrations.DeleteModel(
            name='Company2',
        ),
    ]
